extends:
  - '@commitlint/config-conventional'

rules:
  body-max-length:
    - 2
    - always
    - Infinity
  footer-max-line-length:
    - 2
    - always
    - Infinity
  header-max-length:
    - 2
    - always
    - Infinity
  type-enum:
    - 2
    - always
    - [
        'build',
        'chore',
        'docs',
        'feat',
        'fix',
        'merge',
        'ops',
        'perf',
        'refactor',
        'revert',
        'spike',
        'story',
        'style',
        'subtree',
        'test',
        'wip'
      ]
