project_name: archivista
builds:
  - ldflags:
      - "-s -w"
      - "-extldflags=-zrelro"
      - "-extldflags=-znow"
      - "-extldflags -w -X 'github.com/testifysec/archivista/cmd.Version={{.Tag}}-{{.ShortCommit}}'"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm64
    main: cmd/archivista/main.go
  - ldflags:
      - "-s -w"
      - "-extldflags=-zrelro"
      - "-extldflags=-znow"
      - "-extldflags -w -X 'github.com/testifysec/archivista/cmd.Version={{.Tag}}-{{.ShortCommit}}'"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm64
    main: cmd/archivistactl/main.go
gomod:
  proxy: false
source:
  enabled: true
changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
release:
  draft: true
  extra_files:
    - name_template: witness_linux_amd64
      glob: dist/archivista_linux_amd64_v1/archivista
    - name_template: archivistactl_linux_amd64
      glob: dist/archivistactl_linux_amd64_v1/archivistactl
  prerelease: auto
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"