'**/*.{js,jsx,ts,tsx}':
  - npm run test:web
'subtrees/archivista/**/*.go':
  - npm run test:archivista
'subtrees/go-witness/**/*.go':
  - npm run test:go-witness
'subtrees/witness/**/*.go':
  - npm run test:witness
'judge-api/**/*.go':
  - npm run test:judge-api