'**/*.{js,jsx,ts,tsx}':
  - npm run test:web
'archivista/**/*.go':
  - npm run test:archivista
'go-witness/**/*.go':
  - npm run test:go-witness
'judge-api/**/*.go':
  - npm run test:judge-api
'witness/**/*.go':
  - npm run test:witness