# Copyright 2022 The Archivista Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.9'

services:
  db:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testify
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysqldata:/var/lib/mysql

  archivista:
    build: .
    restart: unless-stopped
    environment:
      ARCHIVISTA_LISTEN_ON: tcp://0.0.0.0:8082
      ARCHIVISTA_ENABLE_SPIFFE: "false"
      ARCHIVISTA_STORAGE_BACKEND: BLOB
      ARCHIVISTA_FILE_DIR: /tmp/archivista/
      ARCHIVISTA_FILE_SERVE_ON: :8081
      ARCHIVISTA_BLOB_STORE_USE_TLS: "false"
      ARCHIVISTA_BLOB_STORE_CREDENTIAL_TYPE: ACCESS_KEY
      ARCHIVISTA_BLOB_STORE_ACCESS_KEY_ID: testifytestifytestify
      ARCHIVISTA_BLOB_STORE_SECRET_ACCESS_KEY_ID: exampleexampleexample
      ARCHIVISTA_BLOB_STORE_BUCKET_NAME: attestations
      ARCHIVISTA_BLOB_STORE_ENDPOINT: minio:9000
      ARCHIVISTA_ENABLE_GRAPHQL: "true"
      ARCHIVISTA_GRAPHQL_WEB_CLIENT_ENABLE: "true"
      ARCHIVISTA_CORS_ALLOW_ORIGINS: "http://localhost:1234"

    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - fileserver:/tmp/archivista

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: testifytestifytestify
      MINIO_ROOT_PASSWORD: exampleexampleexample
    volumes:
      - miniodata:/data

  minio-init:
    image: quay.io/minio/mc
    restart: on-failure
    command: mb --insecure --ignore-existing testminio/attestations
    environment:
      MC_HOST_testminio: http://testifytestifytestify:exampleexampleexample@minio:9000

volumes:
  fileserver:
  miniodata:
  mysqldata:
