apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: base
requires:
  - path: ./skaffold/init.yaml #namespaces
  - path: ./skaffold/local.yaml #services for local development
  - path: ./skaffold/auth.yaml #auth
  - path: ./skaffold/core.yaml #judge-core
---
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: with-observability
requires:
  - configs: ["base"]
  - path: ./skaffold/observability.yaml

