# create a configmap
# version: v0.11.0

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: kratos
    meta.helm.sh/release-namespace: kratos
  labels:
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kratos
    app.kubernetes.io/version: v0.10.1
    helm.sh/chart: kratos-0.26.5
  name: kratos-config-extra
  namespace: kratos
data:
  "kratos-config.yaml": |
    serve:
      public:
        base_url: https://kratos.testifysec.localhost
        cors:
          enabled: true
          allowed_origins:
            - https://*.testifysec.localhost:8077
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
            - Content-Type
          exposed_headers:
            - Content-Type
            - Set-Cookie
    log:
      level: debug
      format: json
      leak_sensitive_values: true
    selfservice:
      flows:
        error:
          ui_url: https://login.testifysec.localhost/error
        settings:
          ui_url: http://login.testifysec.localhost/settings
          privileged_session_max_age: 15m
          required_aal: highest_available
        recovery:
          enabled: true
          ui_url: https://login.testifysec.localhost/recovery
        verification:
          enabled: true
          ui_url: https://login.testifysec.localhost/verification
          after:
            default_browser_return_url: https://login.testifysec.localhost/
        logout:
          after:
            default_browser_return_url: https://login.testifysec.localhost/login
        login:
          ui_url: https://login.testifysec.localhost/login
          lifespan: 10m
          after:
            default_browser_return_url: https://judge.testifysec.localhost:8077
        registration:
          lifespan: 10m
          ui_url: https://login.testifysec.localhost/registration
          after:
            password:
              hooks:
                - hook: session
      default_browser_return_url: https://judge.testifysec.localhost:8077
      allowed_return_urls:
        - https://login.testifysec.localhost
        - https://kratos.testifysec.localhost
        - https://judge.testifysec.localhost
        - https://localhost
        - https://judge.testifysec.localhost:8077

      methods:
        password:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: hydra
                label: Ory
                provider: generic
                client_id: kratos
                client_secret: kratos
                issuer_url: https://hydra.testifysec.localhost/
                scope:
                  - profile
                mapper_url: file:///etc/config/kratos/hydra.jsonnet
              - id: github
                provider: github
                client_id: ce3298f1412e926dbf9e
                client_secret: b90b2f08da8158d9b92921b02b05e3dc395e5eea
                issuer_url: https://github.com
                scope:
                  - user
                mapper_url: file:///etc/config/kratos/github.jsonnet
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9xdWlja3N0YXJ0L2VtYWlsLXBhc3N3b3JkL2lkZW50aXR5LnNjaGVtYS5qc29uIiwKICAiJHNjaGVtYSI6ICJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLAogICJ0aXRsZSI6ICJQZXJzb24iLAogICJ0eXBlIjogIm9iamVjdCIsCiAgInByb3BlcnRpZXMiOiB7CiAgICAidHJhaXRzIjogewogICAgICAidHlwZSI6ICJvYmplY3QiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiZW1haWwiOiB7CiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgImZvcm1hdCI6ICJlbWFpbCIsCiAgICAgICAgICAidGl0bGUiOiAiRS1NYWlsIiwKICAgICAgICAgICJtaW5MZW5ndGgiOiAzLAogICAgICAgICAgIm9yeS5zaC9rcmF0b3MiOiB7CiAgICAgICAgICAgICJjcmVkZW50aWFscyI6IHsKICAgICAgICAgICAgICAicGFzc3dvcmQiOiB7CiAgICAgICAgICAgICAgICAiaWRlbnRpZmllciI6IHRydWUKICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICJ3ZWJhdXRobiI6IHsKICAgICAgICAgICAgICAgICJpZGVudGlmaWVyIjogdHJ1ZQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgInZlcmlmaWNhdGlvbiI6IHsKICAgICAgICAgICAgICAidmlhIjogImVtYWlsIgogICAgICAgICAgICB9CiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAid2Vic2l0ZSI6IHsKICAgICAgICAgICJ0aXRsZSI6ICJXZWJzaXRlIiwKICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAiZm9ybWF0IjogInVyaSIsCiAgICAgICAgICAibWluTGVuZ3RoIjogMTAKICAgICAgICB9LAogICAgICAgICJjb25zZW50IjogewogICAgICAgICAgInRpdGxlIjogIkNvbnNlbnQiLAogICAgICAgICAgInR5cGUiOiAiYm9vbGVhbiIKICAgICAgICB9LAogICAgICAgICJuZXdzbGV0dGVyIjogewogICAgICAgICAgInRpdGxlIjogIk5ld3NsZXR0ZXIiLAogICAgICAgICAgInR5cGUiOiAiYm9vbGVhbiIKICAgICAgICB9CiAgICAgIH0sCiAgICAgICJyZXF1aXJlZCI6IFsKICAgICAgICAiZW1haWwiLAogICAgICAgICJ3ZWJzaXRlIgogICAgICBdLAogICAgICAiYWRkaXRpb25hbFByb3BlcnRpZXMiOiBmYWxzZQogICAgfQogIH0KfQo=
        - id: other
          url: base64://ewogICIkaWQiOiAib3J5Oi8vaWRlbnRpdHktb3RoZXItc2NoZW1hIiwKICAiJHNjaGVtYSI6ICJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLAogICJ0aXRsZSI6ICJJZGVudGl0eU90aGVyU2NoZW1hIiwKICAidHlwZSI6ICJvYmplY3QiLAogICJwcm9wZXJ0aWVzIjogewogICAgInRyYWl0cyI6IHsKICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIm90aGVyIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgIH0sCiAgICAgICAgImVtYWlsIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICJ0aXRsZSI6ICJlbWFpbCIsCiAgICAgICAgICAib3J5LnNoL2tyYXRvcyI6IHsKICAgICAgICAgICAgImNyZWRlbnRpYWxzIjogewogICAgICAgICAgICAgICJwYXNzd29yZCI6IHsKICAgICAgICAgICAgICAgICJpZGVudGlmaWVyIjogdHJ1ZQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgfQogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfSwKICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICJvdGhlciIsCiAgICAgICAgImVtYWlsIgogICAgICBdLAogICAgICAiYWRkaXRpb25hbFByb3BlcnRpZXMiOiB0cnVlCiAgICB9CiAgfQp9
    cookies:
      domain: testifysec.localhost
      path: /
      same_site: Lax
  "hydra.jsonnet": |
    local claims = {
      email_verified: false
    } + std.extVar('claims');

    {
      identity: {
        traits: {
          // Allowing unverified email addresses enables account
          // enumeration attacks, especially if the value is used for
          // e.g. verification or as a password login identifier.
          //
          // Therefore we only return the email if it (a) exists and (b) is marked verified
          // by GitHub.
          [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
        },
      },
    }
  "github.jsonnet": |
    local claims = {
    email_verified: false
    } + std.extVar('claims');
    
    {
      identity: {
        traits: {
                  // Allowing unverified email addresses enables account
                  // enumeration attacks, especially if the value is used for
                  // e.g. verification or as a password login identifier.
                  //
                  // Therefore we only return the email if it (a) exists and (b) is marked verified
                  // by GitHub.
          [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
        },
      },
    }

