apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: archivista
  name:  archivista
  labels:
    app: archivista
spec:
  selector:
    matchLabels:
      app: archivista
  template:
    metadata:
      labels:
        app: archivista
    spec:
      initContainers:
        - name: init-minio-bucket
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc config host add minio http://minio.minio.svc.cluster.local:9000 minio-user minio-password
              mc mb minio/archivista || true
          env:
            - name: MINIO_ACCESS_KEY
              value: minio-user
            - name: MINIO_SECRET_KEY
              value: minio-password
      containers:
        - name: archivista
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          image: registry.gitlab.com/testifysec/judge-platform/archivista
          env:
            - name: ARCHIVISTA_ENABLE_SPIFFE
              value: "False"
            - name: ARCHIVISTA_LISTEN_ON
              value: tcp://0.0.0.0:8082
            - name: ARCHIVISTA_STORAGE_BACKEND
              value: BLOB
            - name: ARCHIVISTA_BLOB_STORE_USE_TLS
              value: "False"
            - name: ARCHIVISTA_BLOB_STORE_ACCESS_KEY_ID
              value: "minio-user"
            - name: ARCHIVISTA_BLOB_STORE_SECRET_ACCESS_KEY_ID
              value: "minio-password"
            - name: ARCHIVISTA_BLOB_STORE_BUCKET_NAME
              value: "archivista"
            - name: ARCHIVISTA_BLOB_STORE_ENDPOINT
              value: minio.minio.svc.cluster.local:9000
            - name: ARCHIVISTA_ENABLE_GRAPHQL
              value: "true"
            - name: ARCHIVISTA_GRAPHQL_WEB_CLIENT_ENABLE
              value: "true"
            - name: ARCHIVISTA_CORS_ALLOW_ORIGINS 
              value: "*"
            - name: MYSQLPASS
              value: "root"
            - name: ARCHIVISTA_SQL_STORE_CONNECTION_STRING
              value: root:root@tcp(mysql.mysql.svc.cluster.local:3306)/archivista
          ports:
            - containerPort: 8082
              protocol: TCP