apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: judge-k8s
build:
  local:
    useBuildkit: false
  artifacts:
  - image: registry.gitlab.com/testifysec/judge-platform/archivista
    context: "../../subtrees/archivista"
    ko:
      dir: "../archivista"
      main: "../archivista/cmd/archivista"
      env:
      - CGO_ENABLED=0
      flags:
      - -trimpath
      ldflags:
      - -extldflags "-static"

  - image: registry.gitlab.com/testifysec/judge-platform/judge-api
    context: "../../judge-api"  
    ko:
      dir: "../judge-api"
      main: "../judge-api/cmd/server"
      env:
      - CGO_ENABLED=0
      flags:
      - -trimpath
      ldflags:
      - -extldflags "-static"

  #web with no hmr
  - image: registry.gitlab.com/testifysec/judge-platform/web
    context: "../../web"
    hooks:
      before:
        - command:
            - ./scripts/build-web.sh
    sync:
      manual:
        - src: "../../web/public/**"
          dest: "/usr/share/nginx/html/"
    docker:
      dockerfile: "Dockerfile"
      buildArgs:
        base_image: "nginx:1.19.2-alpine"

manifests:
  rawYaml:
    - ../k8s/archivista/*.yaml
    - ../k8s/web/*.yaml
    - ../k8s/judge-api/*.yaml
deploy:
  kubectl: {}
