apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: local

manifests:
  rawYaml:
    - ../k8s/coredns/*.yaml
    #dev tools    
    - ../k8s/dev/phpmyadmin/*.yaml
    - ../k8s/cert-manager/*.yaml 

deploy:
  kubectl: {}
  helm:
    hooks:
      before:
        - host:
            command: [ "./scripts/create-hostmount.sh" ]
      after:
        - host:
            command: ["./scripts/create-tls-secret.sh"]

    releases:
      - name: mysql
        namespace: mysql
        createNamespace: true
        skipBuildDependencies: true
        repo: https://charts.bitnami.com/bitnami
        remoteChart: mysql
        version: 9.4.2
        setValues:
          image:
            registry: docker.io
            repository: mysql
            tag: 8.0

          initdbScripts: |
            01-init.sql: |
              CREATE DATABASE IF NOT EXISTS archivista;
              CREATE DATABASE IF NOT EXISTS kratos;
              CREATE DATABASE IF NOT EXISTS judgeapi;
          auth:
            rootPassword: root
          primary:
            podSecurityContext:
              enabled: false
            containerSecurityContext:
              enabled: true
              runAsUser: 0
              runAsNonRoot: false
            persistence:
              enabled: true
              existingClaim: mysql-pv-claim
          metrics:
            enabled: false
          service:
            type: ClusterIP

      - name: minio
        skipBuildDependencies: true
        createNamespace: true
        namespace: minio
        repo: https://charts.min.io/
        remoteChart: minio
        version: 5.0.1
        setValues:
          resources:
            requests:
              memory: 1Gi
          persistence:
            enabled: true
            existingClaim: minio-pvc
            size: 10Gi
          mode: standalone
          rootUser: minio-user
          rootPassword: minio-password


      - name: cert-manager
        namespace: cert-manager
        skipBuildDependencies: true
        createNamespace: true
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: v1.10.0
        setValues:
          installCRDs: true

      - name: mailhog
        namespace: mailhog
        skipBuildDependencies: true
        createNamespace: true
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        version: 5.2.3