// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/in-toto/archivista/ent/attestationpolicy"
	"github.com/in-toto/archivista/ent/statement"
)

// AttestationPolicyCreate is the builder for creating a AttestationPolicy entity.
type AttestationPolicyCreate struct {
	config
	mutation *AttestationPolicyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AttestationPolicyCreate) SetName(v string) *AttestationPolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AttestationPolicyCreate) SetID(v uuid.UUID) *AttestationPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AttestationPolicyCreate) SetNillableID(v *uuid.UUID) *AttestationPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetStatementID sets the "statement" edge to the Statement entity by ID.
func (_c *AttestationPolicyCreate) SetStatementID(id uuid.UUID) *AttestationPolicyCreate {
	_c.mutation.SetStatementID(id)
	return _c
}

// SetNillableStatementID sets the "statement" edge to the Statement entity by ID if the given value is not nil.
func (_c *AttestationPolicyCreate) SetNillableStatementID(id *uuid.UUID) *AttestationPolicyCreate {
	if id != nil {
		_c = _c.SetStatementID(*id)
	}
	return _c
}

// SetStatement sets the "statement" edge to the Statement entity.
func (_c *AttestationPolicyCreate) SetStatement(v *Statement) *AttestationPolicyCreate {
	return _c.SetStatementID(v.ID)
}

// Mutation returns the AttestationPolicyMutation object of the builder.
func (_c *AttestationPolicyCreate) Mutation() *AttestationPolicyMutation {
	return _c.mutation
}

// Save creates the AttestationPolicy in the database.
func (_c *AttestationPolicyCreate) Save(ctx context.Context) (*AttestationPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttestationPolicyCreate) SaveX(ctx context.Context) *AttestationPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttestationPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttestationPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AttestationPolicyCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := attestationpolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttestationPolicyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AttestationPolicy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := attestationpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AttestationPolicy.name": %w`, err)}
		}
	}
	return nil
}

func (_c *AttestationPolicyCreate) sqlSave(ctx context.Context) (*AttestationPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttestationPolicyCreate) createSpec() (*AttestationPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &AttestationPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attestationpolicy.Table, sqlgraph.NewFieldSpec(attestationpolicy.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(attestationpolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.StatementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   attestationpolicy.StatementTable,
			Columns: []string{attestationpolicy.StatementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.statement_policy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttestationPolicyCreateBulk is the builder for creating many AttestationPolicy entities in bulk.
type AttestationPolicyCreateBulk struct {
	config
	err      error
	builders []*AttestationPolicyCreate
}

// Save creates the AttestationPolicy entities in the database.
func (_c *AttestationPolicyCreateBulk) Save(ctx context.Context) ([]*AttestationPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AttestationPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttestationPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttestationPolicyCreateBulk) SaveX(ctx context.Context) []*AttestationPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttestationPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttestationPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
