// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/in-toto/archivista/ent/dsse"
	"github.com/in-toto/archivista/ent/payloaddigest"
	"github.com/in-toto/archivista/ent/predicate"
	"github.com/in-toto/archivista/ent/signature"
	"github.com/in-toto/archivista/ent/statement"
)

// DsseQuery is the builder for querying Dsse entities.
type DsseQuery struct {
	config
	ctx                     *QueryContext
	order                   []dsse.OrderOption
	inters                  []Interceptor
	predicates              []predicate.Dsse
	withStatement           *StatementQuery
	withSignatures          *SignatureQuery
	withPayloadDigests      *PayloadDigestQuery
	withFKs                 bool
	modifiers               []func(*sql.Selector)
	loadTotal               []func(context.Context, []*Dsse) error
	withNamedSignatures     map[string]*SignatureQuery
	withNamedPayloadDigests map[string]*PayloadDigestQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DsseQuery builder.
func (_q *DsseQuery) Where(ps ...predicate.Dsse) *DsseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DsseQuery) Limit(limit int) *DsseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DsseQuery) Offset(offset int) *DsseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DsseQuery) Unique(unique bool) *DsseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DsseQuery) Order(o ...dsse.OrderOption) *DsseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryStatement chains the current query on the "statement" edge.
func (_q *DsseQuery) QueryStatement() *StatementQuery {
	query := (&StatementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dsse.Table, dsse.FieldID, selector),
			sqlgraph.To(statement.Table, statement.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, dsse.StatementTable, dsse.StatementColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySignatures chains the current query on the "signatures" edge.
func (_q *DsseQuery) QuerySignatures() *SignatureQuery {
	query := (&SignatureClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dsse.Table, dsse.FieldID, selector),
			sqlgraph.To(signature.Table, signature.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dsse.SignaturesTable, dsse.SignaturesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPayloadDigests chains the current query on the "payload_digests" edge.
func (_q *DsseQuery) QueryPayloadDigests() *PayloadDigestQuery {
	query := (&PayloadDigestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dsse.Table, dsse.FieldID, selector),
			sqlgraph.To(payloaddigest.Table, payloaddigest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dsse.PayloadDigestsTable, dsse.PayloadDigestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Dsse entity from the query.
// Returns a *NotFoundError when no Dsse was found.
func (_q *DsseQuery) First(ctx context.Context) (*Dsse, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dsse.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DsseQuery) FirstX(ctx context.Context) *Dsse {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Dsse ID from the query.
// Returns a *NotFoundError when no Dsse ID was found.
func (_q *DsseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dsse.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DsseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Dsse entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Dsse entity is found.
// Returns a *NotFoundError when no Dsse entities are found.
func (_q *DsseQuery) Only(ctx context.Context) (*Dsse, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dsse.Label}
	default:
		return nil, &NotSingularError{dsse.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DsseQuery) OnlyX(ctx context.Context) *Dsse {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Dsse ID in the query.
// Returns a *NotSingularError when more than one Dsse ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DsseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dsse.Label}
	default:
		err = &NotSingularError{dsse.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DsseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Dsses.
func (_q *DsseQuery) All(ctx context.Context) ([]*Dsse, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Dsse, *DsseQuery]()
	return withInterceptors[[]*Dsse](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DsseQuery) AllX(ctx context.Context) []*Dsse {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Dsse IDs.
func (_q *DsseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(dsse.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DsseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DsseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DsseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DsseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DsseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DsseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DsseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DsseQuery) Clone() *DsseQuery {
	if _q == nil {
		return nil
	}
	return &DsseQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]dsse.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.Dsse{}, _q.predicates...),
		withStatement:      _q.withStatement.Clone(),
		withSignatures:     _q.withSignatures.Clone(),
		withPayloadDigests: _q.withPayloadDigests.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithStatement tells the query-builder to eager-load the nodes that are connected to
// the "statement" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DsseQuery) WithStatement(opts ...func(*StatementQuery)) *DsseQuery {
	query := (&StatementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStatement = query
	return _q
}

// WithSignatures tells the query-builder to eager-load the nodes that are connected to
// the "signatures" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DsseQuery) WithSignatures(opts ...func(*SignatureQuery)) *DsseQuery {
	query := (&SignatureClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSignatures = query
	return _q
}

// WithPayloadDigests tells the query-builder to eager-load the nodes that are connected to
// the "payload_digests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DsseQuery) WithPayloadDigests(opts ...func(*PayloadDigestQuery)) *DsseQuery {
	query := (&PayloadDigestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPayloadDigests = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Dsse.Query().
//		GroupBy(dsse.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DsseQuery) GroupBy(field string, fields ...string) *DsseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DsseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dsse.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Dsse.Query().
//		Select(dsse.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *DsseQuery) Select(fields ...string) *DsseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DsseSelect{DsseQuery: _q}
	sbuild.label = dsse.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DsseSelect configured with the given aggregations.
func (_q *DsseQuery) Aggregate(fns ...AggregateFunc) *DsseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DsseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dsse.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DsseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Dsse, error) {
	var (
		nodes       = []*Dsse{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withStatement != nil,
			_q.withSignatures != nil,
			_q.withPayloadDigests != nil,
		}
	)
	if _q.withStatement != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, dsse.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Dsse).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Dsse{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withStatement; query != nil {
		if err := _q.loadStatement(ctx, query, nodes, nil,
			func(n *Dsse, e *Statement) { n.Edges.Statement = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSignatures; query != nil {
		if err := _q.loadSignatures(ctx, query, nodes,
			func(n *Dsse) { n.Edges.Signatures = []*Signature{} },
			func(n *Dsse, e *Signature) { n.Edges.Signatures = append(n.Edges.Signatures, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPayloadDigests; query != nil {
		if err := _q.loadPayloadDigests(ctx, query, nodes,
			func(n *Dsse) { n.Edges.PayloadDigests = []*PayloadDigest{} },
			func(n *Dsse, e *PayloadDigest) { n.Edges.PayloadDigests = append(n.Edges.PayloadDigests, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedSignatures {
		if err := _q.loadSignatures(ctx, query, nodes,
			func(n *Dsse) { n.appendNamedSignatures(name) },
			func(n *Dsse, e *Signature) { n.appendNamedSignatures(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedPayloadDigests {
		if err := _q.loadPayloadDigests(ctx, query, nodes,
			func(n *Dsse) { n.appendNamedPayloadDigests(name) },
			func(n *Dsse, e *PayloadDigest) { n.appendNamedPayloadDigests(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DsseQuery) loadStatement(ctx context.Context, query *StatementQuery, nodes []*Dsse, init func(*Dsse), assign func(*Dsse, *Statement)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Dsse)
	for i := range nodes {
		if nodes[i].dsse_statement == nil {
			continue
		}
		fk := *nodes[i].dsse_statement
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(statement.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "dsse_statement" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DsseQuery) loadSignatures(ctx context.Context, query *SignatureQuery, nodes []*Dsse, init func(*Dsse), assign func(*Dsse, *Signature)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Dsse)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Signature(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(dsse.SignaturesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.dsse_signatures
		if fk == nil {
			return fmt.Errorf(`foreign-key "dsse_signatures" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dsse_signatures" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DsseQuery) loadPayloadDigests(ctx context.Context, query *PayloadDigestQuery, nodes []*Dsse, init func(*Dsse), assign func(*Dsse, *PayloadDigest)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Dsse)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PayloadDigest(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(dsse.PayloadDigestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.dsse_payload_digests
		if fk == nil {
			return fmt.Errorf(`foreign-key "dsse_payload_digests" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dsse_payload_digests" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DsseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DsseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dsse.Table, dsse.Columns, sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dsse.FieldID)
		for i := range fields {
			if fields[i] != dsse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DsseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dsse.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dsse.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedSignatures tells the query-builder to eager-load the nodes that are connected to the "signatures"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *DsseQuery) WithNamedSignatures(name string, opts ...func(*SignatureQuery)) *DsseQuery {
	query := (&SignatureClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedSignatures == nil {
		_q.withNamedSignatures = make(map[string]*SignatureQuery)
	}
	_q.withNamedSignatures[name] = query
	return _q
}

// WithNamedPayloadDigests tells the query-builder to eager-load the nodes that are connected to the "payload_digests"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *DsseQuery) WithNamedPayloadDigests(name string, opts ...func(*PayloadDigestQuery)) *DsseQuery {
	query := (&PayloadDigestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedPayloadDigests == nil {
		_q.withNamedPayloadDigests = make(map[string]*PayloadDigestQuery)
	}
	_q.withNamedPayloadDigests[name] = query
	return _q
}

// DsseGroupBy is the group-by builder for Dsse entities.
type DsseGroupBy struct {
	selector
	build *DsseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DsseGroupBy) Aggregate(fns ...AggregateFunc) *DsseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DsseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DsseQuery, *DsseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DsseGroupBy) sqlScan(ctx context.Context, root *DsseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DsseSelect is the builder for selecting fields of Dsse entities.
type DsseSelect struct {
	*DsseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DsseSelect) Aggregate(fns ...AggregateFunc) *DsseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DsseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DsseQuery, *DsseSelect](ctx, _s.DsseQuery, _s, _s.inters, v)
}

func (_s *DsseSelect) sqlScan(ctx context.Context, root *DsseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
