// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/dsse"
	"github.com/in-toto/archivista/ent/metadata"
	"github.com/in-toto/archivista/ent/predicate"
)

// MetadataUpdate is the builder for updating Metadata entities.
type MetadataUpdate struct {
	config
	hooks    []Hook
	mutation *MetadataMutation
}

// Where appends a list predicates to the MetadataUpdate builder.
func (mu *MetadataUpdate) Where(ps ...predicate.Metadata) *MetadataUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetKey sets the "key" field.
func (mu *MetadataUpdate) SetKey(s string) *MetadataUpdate {
	mu.mutation.SetKey(s)
	return mu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (mu *MetadataUpdate) SetNillableKey(s *string) *MetadataUpdate {
	if s != nil {
		mu.SetKey(*s)
	}
	return mu
}

// SetValue sets the "value" field.
func (mu *MetadataUpdate) SetValue(s string) *MetadataUpdate {
	mu.mutation.SetValue(s)
	return mu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (mu *MetadataUpdate) SetNillableValue(s *string) *MetadataUpdate {
	if s != nil {
		mu.SetValue(*s)
	}
	return mu
}

// AddEnvelopeIDs adds the "envelope" edge to the Dsse entity by IDs.
func (mu *MetadataUpdate) AddEnvelopeIDs(ids ...int) *MetadataUpdate {
	mu.mutation.AddEnvelopeIDs(ids...)
	return mu
}

// AddEnvelope adds the "envelope" edges to the Dsse entity.
func (mu *MetadataUpdate) AddEnvelope(d ...*Dsse) *MetadataUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return mu.AddEnvelopeIDs(ids...)
}

// Mutation returns the MetadataMutation object of the builder.
func (mu *MetadataUpdate) Mutation() *MetadataMutation {
	return mu.mutation
}

// ClearEnvelope clears all "envelope" edges to the Dsse entity.
func (mu *MetadataUpdate) ClearEnvelope() *MetadataUpdate {
	mu.mutation.ClearEnvelope()
	return mu
}

// RemoveEnvelopeIDs removes the "envelope" edge to Dsse entities by IDs.
func (mu *MetadataUpdate) RemoveEnvelopeIDs(ids ...int) *MetadataUpdate {
	mu.mutation.RemoveEnvelopeIDs(ids...)
	return mu
}

// RemoveEnvelope removes "envelope" edges to Dsse entities.
func (mu *MetadataUpdate) RemoveEnvelope(d ...*Dsse) *MetadataUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return mu.RemoveEnvelopeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MetadataUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MetadataUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MetadataUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MetadataUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MetadataUpdate) check() error {
	if v, ok := mu.mutation.Key(); ok {
		if err := metadata.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Metadata.key": %w`, err)}
		}
	}
	if v, ok := mu.mutation.Value(); ok {
		if err := metadata.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Metadata.value": %w`, err)}
		}
	}
	return nil
}

func (mu *MetadataUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(metadata.Table, metadata.Columns, sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Key(); ok {
		_spec.SetField(metadata.FieldKey, field.TypeString, value)
	}
	if value, ok := mu.mutation.Value(); ok {
		_spec.SetField(metadata.FieldValue, field.TypeString, value)
	}
	if mu.mutation.EnvelopeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   metadata.EnvelopeTable,
			Columns: metadata.EnvelopePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedEnvelopeIDs(); len(nodes) > 0 && !mu.mutation.EnvelopeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   metadata.EnvelopeTable,
			Columns: metadata.EnvelopePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.EnvelopeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   metadata.EnvelopeTable,
			Columns: metadata.EnvelopePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MetadataUpdateOne is the builder for updating a single Metadata entity.
type MetadataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetadataMutation
}

// SetKey sets the "key" field.
func (muo *MetadataUpdateOne) SetKey(s string) *MetadataUpdateOne {
	muo.mutation.SetKey(s)
	return muo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (muo *MetadataUpdateOne) SetNillableKey(s *string) *MetadataUpdateOne {
	if s != nil {
		muo.SetKey(*s)
	}
	return muo
}

// SetValue sets the "value" field.
func (muo *MetadataUpdateOne) SetValue(s string) *MetadataUpdateOne {
	muo.mutation.SetValue(s)
	return muo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (muo *MetadataUpdateOne) SetNillableValue(s *string) *MetadataUpdateOne {
	if s != nil {
		muo.SetValue(*s)
	}
	return muo
}

// AddEnvelopeIDs adds the "envelope" edge to the Dsse entity by IDs.
func (muo *MetadataUpdateOne) AddEnvelopeIDs(ids ...int) *MetadataUpdateOne {
	muo.mutation.AddEnvelopeIDs(ids...)
	return muo
}

// AddEnvelope adds the "envelope" edges to the Dsse entity.
func (muo *MetadataUpdateOne) AddEnvelope(d ...*Dsse) *MetadataUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return muo.AddEnvelopeIDs(ids...)
}

// Mutation returns the MetadataMutation object of the builder.
func (muo *MetadataUpdateOne) Mutation() *MetadataMutation {
	return muo.mutation
}

// ClearEnvelope clears all "envelope" edges to the Dsse entity.
func (muo *MetadataUpdateOne) ClearEnvelope() *MetadataUpdateOne {
	muo.mutation.ClearEnvelope()
	return muo
}

// RemoveEnvelopeIDs removes the "envelope" edge to Dsse entities by IDs.
func (muo *MetadataUpdateOne) RemoveEnvelopeIDs(ids ...int) *MetadataUpdateOne {
	muo.mutation.RemoveEnvelopeIDs(ids...)
	return muo
}

// RemoveEnvelope removes "envelope" edges to Dsse entities.
func (muo *MetadataUpdateOne) RemoveEnvelope(d ...*Dsse) *MetadataUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return muo.RemoveEnvelopeIDs(ids...)
}

// Where appends a list predicates to the MetadataUpdate builder.
func (muo *MetadataUpdateOne) Where(ps ...predicate.Metadata) *MetadataUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MetadataUpdateOne) Select(field string, fields ...string) *MetadataUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Metadata entity.
func (muo *MetadataUpdateOne) Save(ctx context.Context) (*Metadata, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MetadataUpdateOne) SaveX(ctx context.Context) *Metadata {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MetadataUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MetadataUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MetadataUpdateOne) check() error {
	if v, ok := muo.mutation.Key(); ok {
		if err := metadata.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Metadata.key": %w`, err)}
		}
	}
	if v, ok := muo.mutation.Value(); ok {
		if err := metadata.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Metadata.value": %w`, err)}
		}
	}
	return nil
}

func (muo *MetadataUpdateOne) sqlSave(ctx context.Context) (_node *Metadata, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(metadata.Table, metadata.Columns, sqlgraph.NewFieldSpec(metadata.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Metadata.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, metadata.FieldID)
		for _, f := range fields {
			if !metadata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != metadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Key(); ok {
		_spec.SetField(metadata.FieldKey, field.TypeString, value)
	}
	if value, ok := muo.mutation.Value(); ok {
		_spec.SetField(metadata.FieldValue, field.TypeString, value)
	}
	if muo.mutation.EnvelopeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   metadata.EnvelopeTable,
			Columns: metadata.EnvelopePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedEnvelopeIDs(); len(nodes) > 0 && !muo.mutation.EnvelopeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   metadata.EnvelopeTable,
			Columns: metadata.EnvelopePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.EnvelopeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   metadata.EnvelopeTable,
			Columns: metadata.EnvelopePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dsse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Metadata{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
