// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/omnitrail"
	"github.com/in-toto/archivista/ent/predicate"
)

// OmnitrailDelete is the builder for deleting a Omnitrail entity.
type OmnitrailDelete struct {
	config
	hooks    []Hook
	mutation *OmnitrailMutation
}

// Where appends a list predicates to the OmnitrailDelete builder.
func (od *OmnitrailDelete) Where(ps ...predicate.Omnitrail) *OmnitrailDelete {
	od.mutation.Where(ps...)
	return od
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (od *OmnitrailDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, od.sqlExec, od.mutation, od.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (od *OmnitrailDelete) ExecX(ctx context.Context) int {
	n, err := od.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (od *OmnitrailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(omnitrail.Table, sqlgraph.NewFieldSpec(omnitrail.FieldID, field.TypeUUID))
	if ps := od.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, od.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	od.mutation.done = true
	return affected, err
}

// OmnitrailDeleteOne is the builder for deleting a single Omnitrail entity.
type OmnitrailDeleteOne struct {
	od *OmnitrailDelete
}

// Where appends a list predicates to the OmnitrailDelete builder.
func (odo *OmnitrailDeleteOne) Where(ps ...predicate.Omnitrail) *OmnitrailDeleteOne {
	odo.od.mutation.Where(ps...)
	return odo
}

// Exec executes the deletion query.
func (odo *OmnitrailDeleteOne) Exec(ctx context.Context) error {
	n, err := odo.od.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{omnitrail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (odo *OmnitrailDeleteOne) ExecX(ctx context.Context) {
	if err := odo.Exec(ctx); err != nil {
		panic(err)
	}
}
