// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/predicate"
	"github.com/in-toto/archivista/ent/vexdocument"
	"github.com/in-toto/archivista/ent/vexstatement"
)

// VexStatementQuery is the builder for querying VexStatement entities.
type VexStatementQuery struct {
	config
	ctx             *QueryContext
	order           []vexstatement.OrderOption
	inters          []Interceptor
	predicates      []predicate.VexStatement
	withVexDocument *VexDocumentQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	loadTotal       []func(context.Context, []*VexStatement) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VexStatementQuery builder.
func (vsq *VexStatementQuery) Where(ps ...predicate.VexStatement) *VexStatementQuery {
	vsq.predicates = append(vsq.predicates, ps...)
	return vsq
}

// Limit the number of records to be returned by this query.
func (vsq *VexStatementQuery) Limit(limit int) *VexStatementQuery {
	vsq.ctx.Limit = &limit
	return vsq
}

// Offset to start from.
func (vsq *VexStatementQuery) Offset(offset int) *VexStatementQuery {
	vsq.ctx.Offset = &offset
	return vsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vsq *VexStatementQuery) Unique(unique bool) *VexStatementQuery {
	vsq.ctx.Unique = &unique
	return vsq
}

// Order specifies how the records should be ordered.
func (vsq *VexStatementQuery) Order(o ...vexstatement.OrderOption) *VexStatementQuery {
	vsq.order = append(vsq.order, o...)
	return vsq
}

// QueryVexDocument chains the current query on the "vex_document" edge.
func (vsq *VexStatementQuery) QueryVexDocument() *VexDocumentQuery {
	query := (&VexDocumentClient{config: vsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vexstatement.Table, vexstatement.FieldID, selector),
			sqlgraph.To(vexdocument.Table, vexdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, vexstatement.VexDocumentTable, vexstatement.VexDocumentColumn),
		)
		fromU = sqlgraph.SetNeighbors(vsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VexStatement entity from the query.
// Returns a *NotFoundError when no VexStatement was found.
func (vsq *VexStatementQuery) First(ctx context.Context) (*VexStatement, error) {
	nodes, err := vsq.Limit(1).All(setContextOp(ctx, vsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vexstatement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vsq *VexStatementQuery) FirstX(ctx context.Context) *VexStatement {
	node, err := vsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VexStatement ID from the query.
// Returns a *NotFoundError when no VexStatement ID was found.
func (vsq *VexStatementQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vsq.Limit(1).IDs(setContextOp(ctx, vsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vexstatement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vsq *VexStatementQuery) FirstIDX(ctx context.Context) int {
	id, err := vsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VexStatement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VexStatement entity is found.
// Returns a *NotFoundError when no VexStatement entities are found.
func (vsq *VexStatementQuery) Only(ctx context.Context) (*VexStatement, error) {
	nodes, err := vsq.Limit(2).All(setContextOp(ctx, vsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vexstatement.Label}
	default:
		return nil, &NotSingularError{vexstatement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vsq *VexStatementQuery) OnlyX(ctx context.Context) *VexStatement {
	node, err := vsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VexStatement ID in the query.
// Returns a *NotSingularError when more than one VexStatement ID is found.
// Returns a *NotFoundError when no entities are found.
func (vsq *VexStatementQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vsq.Limit(2).IDs(setContextOp(ctx, vsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vexstatement.Label}
	default:
		err = &NotSingularError{vexstatement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vsq *VexStatementQuery) OnlyIDX(ctx context.Context) int {
	id, err := vsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VexStatements.
func (vsq *VexStatementQuery) All(ctx context.Context) ([]*VexStatement, error) {
	ctx = setContextOp(ctx, vsq.ctx, "All")
	if err := vsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VexStatement, *VexStatementQuery]()
	return withInterceptors[[]*VexStatement](ctx, vsq, qr, vsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vsq *VexStatementQuery) AllX(ctx context.Context) []*VexStatement {
	nodes, err := vsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VexStatement IDs.
func (vsq *VexStatementQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vsq.ctx.Unique == nil && vsq.path != nil {
		vsq.Unique(true)
	}
	ctx = setContextOp(ctx, vsq.ctx, "IDs")
	if err = vsq.Select(vexstatement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vsq *VexStatementQuery) IDsX(ctx context.Context) []int {
	ids, err := vsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vsq *VexStatementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vsq.ctx, "Count")
	if err := vsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vsq, querierCount[*VexStatementQuery](), vsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vsq *VexStatementQuery) CountX(ctx context.Context) int {
	count, err := vsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vsq *VexStatementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vsq.ctx, "Exist")
	switch _, err := vsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vsq *VexStatementQuery) ExistX(ctx context.Context) bool {
	exist, err := vsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VexStatementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vsq *VexStatementQuery) Clone() *VexStatementQuery {
	if vsq == nil {
		return nil
	}
	return &VexStatementQuery{
		config:          vsq.config,
		ctx:             vsq.ctx.Clone(),
		order:           append([]vexstatement.OrderOption{}, vsq.order...),
		inters:          append([]Interceptor{}, vsq.inters...),
		predicates:      append([]predicate.VexStatement{}, vsq.predicates...),
		withVexDocument: vsq.withVexDocument.Clone(),
		// clone intermediate query.
		sql:  vsq.sql.Clone(),
		path: vsq.path,
	}
}

// WithVexDocument tells the query-builder to eager-load the nodes that are connected to
// the "vex_document" edge. The optional arguments are used to configure the query builder of the edge.
func (vsq *VexStatementQuery) WithVexDocument(opts ...func(*VexDocumentQuery)) *VexStatementQuery {
	query := (&VexDocumentClient{config: vsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vsq.withVexDocument = query
	return vsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VexID string `json:"vex_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VexStatement.Query().
//		GroupBy(vexstatement.FieldVexID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vsq *VexStatementQuery) GroupBy(field string, fields ...string) *VexStatementGroupBy {
	vsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VexStatementGroupBy{build: vsq}
	grbuild.flds = &vsq.ctx.Fields
	grbuild.label = vexstatement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VexID string `json:"vex_id,omitempty"`
//	}
//
//	client.VexStatement.Query().
//		Select(vexstatement.FieldVexID).
//		Scan(ctx, &v)
func (vsq *VexStatementQuery) Select(fields ...string) *VexStatementSelect {
	vsq.ctx.Fields = append(vsq.ctx.Fields, fields...)
	sbuild := &VexStatementSelect{VexStatementQuery: vsq}
	sbuild.label = vexstatement.Label
	sbuild.flds, sbuild.scan = &vsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VexStatementSelect configured with the given aggregations.
func (vsq *VexStatementQuery) Aggregate(fns ...AggregateFunc) *VexStatementSelect {
	return vsq.Select().Aggregate(fns...)
}

func (vsq *VexStatementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vsq); err != nil {
				return err
			}
		}
	}
	for _, f := range vsq.ctx.Fields {
		if !vexstatement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vsq.path != nil {
		prev, err := vsq.path(ctx)
		if err != nil {
			return err
		}
		vsq.sql = prev
	}
	return nil
}

func (vsq *VexStatementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VexStatement, error) {
	var (
		nodes       = []*VexStatement{}
		withFKs     = vsq.withFKs
		_spec       = vsq.querySpec()
		loadedTypes = [1]bool{
			vsq.withVexDocument != nil,
		}
	)
	if vsq.withVexDocument != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, vexstatement.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VexStatement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VexStatement{config: vsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(vsq.modifiers) > 0 {
		_spec.Modifiers = vsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vsq.withVexDocument; query != nil {
		if err := vsq.loadVexDocument(ctx, query, nodes, nil,
			func(n *VexStatement, e *VexDocument) { n.Edges.VexDocument = e }); err != nil {
			return nil, err
		}
	}
	for i := range vsq.loadTotal {
		if err := vsq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vsq *VexStatementQuery) loadVexDocument(ctx context.Context, query *VexDocumentQuery, nodes []*VexStatement, init func(*VexStatement), assign func(*VexStatement, *VexDocument)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*VexStatement)
	for i := range nodes {
		if nodes[i].vex_document_vex_statements == nil {
			continue
		}
		fk := *nodes[i].vex_document_vex_statements
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(vexdocument.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vex_document_vex_statements" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vsq *VexStatementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vsq.querySpec()
	if len(vsq.modifiers) > 0 {
		_spec.Modifiers = vsq.modifiers
	}
	_spec.Node.Columns = vsq.ctx.Fields
	if len(vsq.ctx.Fields) > 0 {
		_spec.Unique = vsq.ctx.Unique != nil && *vsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vsq.driver, _spec)
}

func (vsq *VexStatementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(vexstatement.Table, vexstatement.Columns, sqlgraph.NewFieldSpec(vexstatement.FieldID, field.TypeInt))
	_spec.From = vsq.sql
	if unique := vsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vsq.path != nil {
		_spec.Unique = true
	}
	if fields := vsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vexstatement.FieldID)
		for i := range fields {
			if fields[i] != vexstatement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vsq *VexStatementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vsq.driver.Dialect())
	t1 := builder.Table(vexstatement.Table)
	columns := vsq.ctx.Fields
	if len(columns) == 0 {
		columns = vexstatement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vsq.sql != nil {
		selector = vsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vsq.ctx.Unique != nil && *vsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vsq.predicates {
		p(selector)
	}
	for _, p := range vsq.order {
		p(selector)
	}
	if offset := vsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VexStatementGroupBy is the group-by builder for VexStatement entities.
type VexStatementGroupBy struct {
	selector
	build *VexStatementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vsgb *VexStatementGroupBy) Aggregate(fns ...AggregateFunc) *VexStatementGroupBy {
	vsgb.fns = append(vsgb.fns, fns...)
	return vsgb
}

// Scan applies the selector query and scans the result into the given value.
func (vsgb *VexStatementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vsgb.build.ctx, "GroupBy")
	if err := vsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VexStatementQuery, *VexStatementGroupBy](ctx, vsgb.build, vsgb, vsgb.build.inters, v)
}

func (vsgb *VexStatementGroupBy) sqlScan(ctx context.Context, root *VexStatementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vsgb.fns))
	for _, fn := range vsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vsgb.flds)+len(vsgb.fns))
		for _, f := range *vsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VexStatementSelect is the builder for selecting fields of VexStatement entities.
type VexStatementSelect struct {
	*VexStatementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vss *VexStatementSelect) Aggregate(fns ...AggregateFunc) *VexStatementSelect {
	vss.fns = append(vss.fns, fns...)
	return vss
}

// Scan applies the selector query and scans the result into the given value.
func (vss *VexStatementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vss.ctx, "Select")
	if err := vss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VexStatementQuery, *VexStatementSelect](ctx, vss.VexStatementQuery, vss, vss.inters, v)
}

func (vss *VexStatementSelect) sqlScan(ctx context.Context, root *VexStatementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vss.fns))
	for _, fn := range vss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
