-- Create "metadata" table
CREATE TABLE "metadata" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "key" character varying NOT NULL, "value" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "metadata_key_value" to table: "metadata"
CREATE UNIQUE INDEX "metadata_key_value" ON "metadata" ("key", "value");
-- Create "dsse_metadata" table
CREATE TABLE "dsse_metadata" ("dsse_id" bigint NOT NULL, "metadata_id" bigint NOT NULL, PRIMARY KEY ("dsse_id", "metadata_id"), CONSTRAINT "dsse_metadata_dsse_id" FOREIGN KEY ("dsse_id") REFERENCES "dsses" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dsse_metadata_metadata_id" FOREIGN KEY ("metadata_id") REFERENCES "metadata" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
