# Copyright 2022 The Witness Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: release
on: [push, pull_request]

permissions:
  contents: read

jobs:
  fmt:
    uses: ./.github/workflows/witness.yml
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
    with:
      pull_request: ${{ github.event_name == 'pull_request' }}
      step: fmt
      attestations: "git github environment"
      command: go fmt ./...

  sast:
    needs: [fmt]
    uses: ./.github/workflows/witness.yml
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
    with:
      pull_request: ${{ github.event_name == 'pull_request' }}
      step: sast
      attestations: "git github environment"
      command: go vet ./...

  unit-test:
    needs: [fmt]
    uses: ./.github/workflows/witness.yml
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
    with:
      pull_request: ${{ github.event_name == 'pull_request' }}
      step: unit-test
      attestations: "git github environment"
      command: go test -v -coverprofile=profile.cov -covermode=atomic ./...
      artifact-upload-name: profile.cov
      artifact-upload-path: profile.cov

  release:
    needs: [fmt, sast, unit-test]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
