# Copyright 2023 The Archivista Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
    workflow_call:
        inputs:
            pull_request:
                required: true
                type: boolean
            command:
                required: true
                type: string
            step:
                required: true
                type: string
            attestations:
                required: true
                type: string

permissions:
  contents: read

jobs:
    witness:
        runs-on: ubuntu-22.04
        permissions:
          contents: read
          id-token: write
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
            with:
              egress-policy: audit

          - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
            with:
              go-version-file: "go.mod"

          - if: ${{ inputs.pull_request == false }}
            uses: testifysec/witness-run-action@7aa15e327829f1f2a523365c564c948d5dde69dd
            with:
              witness-install-dir: /opt/witness
              version: 0.9.1
              step: ${{ inputs.step }}
              attestations: ${{ inputs.attestations }}
              command: /bin/sh -c "${{ inputs.command }}"

          - if: ${{ inputs.pull_request == true }}
            run: ${{ inputs.command }}

          - if: ${{ inputs.step == 'tests' }}
            uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
