image: registry.gitlab.com/testifysec/docker-images/npm:v0.0.1
variables: 
  WITNESS_ENABLE: "true"
  ARCHIVIST_ENABLE: "true"
  WITNESS_STEP: $CI_JOB_STAGE
  WITNESS_ATTESTORS: gitlab gcp-iit git

stages:
  - deps
  - quality checks
  - build
  - package
  - attest

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

deps:
  stage: deps
  script:
      - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - .npm/
      - node_modules/
    when: always

# lint:
#   stage: quality checks
#   script:
#     - npm run lint
#   allow_failure: true


# style:
#   stage: quality checks
#   script:
#     - npm run style
#   allow_failure: true

build:
  artifacts:
    paths:
      - public/
  stage: build
  script:
    - npm run build

package:
  artifacts:
    paths:
      - "out.tar"
  dependencies:
    - build
  variables: 
    WITNESS_ENABLE: "true"
    WITNESS_ATTESTORS: gitlab gcp-iit git oci
  stage: package
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --cache-repo "${CI_REGISTRY}/${CI_REGISTRY_IMAGE}"
      --cache=true
      --tarPath "${CI_PROJECT_DIR}/out.tar"
  rules:
    - if: $CI_COMMIT_TAG

